### ISSUE TITLE
Even faster with memoization?

### ISSUE THREAD

**Issue by jjb** [Shopify/symbol-fstring#9]
I was curious about the implementation of rb_sym2str

I found this test: https://github.com/ruby/ruby/blob/d92f09a5eea009fa28cd046e9d0eb698e3d94c5c/spec/ruby/optional/capi/symbol_spec.rb#L151-L155

Which doesn't demonstrate much. I found this definition: https://github.com/ruby/ruby/blob/d92f09a5eea009fa28cd046e9d0eb698e3d94c5c/string.c#L11086-L11104

Which has a blank body. So I'm guessing some sort of macros or aliasing is going on that I don't understand. But it does have nice docs. The only guarantee it offers is that the string is frozen, not that the work done to produce or find the string, whatever that may be, is cached.

So now I'm curious, does the improved performance of the method only come from ruby's general benefit of always reusing frozen strings, but doesn't skip over other possible work? i.e. does it calculate the string in C, and then before making a new ruby string, check the global frozen collection and reuse it? or does it not calculate the string in the first place because it's cached?

So i wondered, what if we did some good old fashioned memoization. I tried a memoization implementation as shown below (commented out), but it wasn't possible because Symbols are frozen. So I did a hardcoded string at first to benchmark, and it is faster.

I also tried a memoization implementation where the values are stored in class-level `@@symbol_name_cache` (not shown below). This one was slower than to_s, not sure if because the concept of memoizing this is unneeded and adds overhead vs rb_sym2str, or because of something inefficient about class variables.

Below is some code demonstrating my experiments. I made a "FastSymbol" wrapper class so I can sort of try my memoization code. It compares well with the delegated methods, but the delegated methods are also slower than the raw methods in the first benchmark, and the memoized method is slower than raw `name`.

So, maybe if my suspicions are correct, the only way to make memoization faster than name is to implement it in C? Depends on the implementation of rb_sym2str, if someone could point me to that I could maybe make better experiments... or deem this all irrelevant.

```ruby
# frozen_string_literal: true
require 'benchmark/ips'

class Symbol
  # FrozenError: can't modify frozen Symbol: :foo
  # def memoized_name
  #  @memoized_name ||= name
  # end

  def hardcoded = "foo".freeze
end

class FastSymbol
  def initialize(symbol) = @symbol = symbol
  def to_s = @symbol.to_s
  def name = @symbol.name
  def memoized_name = @memoized_name ||= name
end

foo = :foo
Benchmark.ips do |bench|
  bench.report("Symbol#to_s") { foo.to_s }
  bench.report("Symbol#name") { foo.name }
  bench.report("Symbol#hardcoded") { foo.hardcoded }
end

fast_foo = FastSymbol.new(:foo)
Benchmark.ips do |bench|
  bench.report("FastSymbol#to_s") { fast_foo.to_s }
  bench.report("FastSymbol#name") { fast_foo.name }
  bench.report("FastSymbol#memoized_name") { fast_foo.memoized_name }
end
```

```
         Symbol#to_s     13.210M (± 3.9%) i/s -     67.167M in   5.093497s
         Symbol#name     19.005M (± 0.7%) i/s -     95.399M in   5.019920s
    Symbol#hardcoded     20.009M (± 0.6%) i/s -    101.662M in   5.081064s
```
```
     FastSymbol#to_s     10.758M (± 5.8%) i/s -     54.026M in   5.043775s
     FastSymbol#name     13.863M (± 7.5%) i/s -     69.533M in   5.052987s
FastSymbol#memoized_name
                         17.704M (± 3.2%) i/s -     88.629M in   5.012618s
```

**Comment by jjb** [comment]
Thanks! wild, I wonder why I couldn't find that definition in github or IDE search.

> So for dynamic symbols it's just a pointer dereference, for static symbols, it's a hash lookup.

Yep, I don't think we're getting any fast than that! 😄 

>  Ruby side of the implementation could potentially be improved

looks like alias doesn't add any overhead

```ruby
# frozen_string_literal: true
require 'benchmark/ips'

Symbol.alias_method(:name2, :name)

foo = :foo
Benchmark.ips do |bench|
  bench.report("Symbol#name") { foo.name }
  bench.report("Symbol#name2") { foo.name2 }
end
```

```
         Symbol#name     19.048M (± 0.8%) i/s -     95.485M in   5.013126s
        Symbol#name2     19.059M (± 0.7%) i/s -     96.966M in   5.088060s
```

**Comment by casperisfine** [comment]
Closing as I don't think there's anything actionable here.
